/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package Aula6;

/**
 *
 * @author aluno
 */
public class AreaQuadrado {

    public static void main(String[] args) {
        Quadrado oQuad = new Quadrado(3);
        
        System.out.println("Area: "      + oQuad.getArea());
        System.out.println("Perimetro: " + oQuad.getPerimetro());
        
    }
}
